[package]
name = "parser"
version = "0.1.0"
edition = "2024"

[dependencies]
bumpalo = { version = "3.17.0", features = ["collections"] }
indoc = "2.0.6"
leb128fmt = "0.1.0"
owo-colors = "4.2.0"
string-interner = "0.19.0"
