(module
  (func $add (param $x i32) (param $y i32) (result i32)
    (local.get $x)
    (local.get $y)
    (i32.add))
  (func $main (export "main") (result i32)
    (local $a i32) (local $x i32) (local $y i32)
    (i32.const 5)
    (local.set $a)
    (i32.const 2)
    (i32.const 2)
    (call $add)
    (local.set $x)
    (i32.const 3)
    (i32.const 3)
    (call $add)
    (i32.const 2)
    (i32.add)
    (local.set $y)
    (i32.const 532523)))
